name: echo workspace
on:
  push:
    branches: [master]

jobs:
  build:
    name: echo workspace
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          repository: calmandhelp/abarg
          ref: master
          token: ${{ secrets.READ_WRITE_HOOK_RIGHTS }}
      - name: cat
        run: cat Makefile
