name: echo workspace
on:
  push:
    branches: [master]

jobs:
  build:
    name: echo workspace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo $GITHUB_WORKSPACE
